spring:
  datasource:
    url: jdbc:postgresql://104.248.133.133:5432/educa
    username: educa
    password: educa
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  jackson:
    time-zone: Europe/Moscow

assistant:
  file_id: asst_WYyT62unT8ej1QE6p9hTZBKT
  text_id: asst_E9qhIty4vWCat7Hc8nrWa1SS
  answer_id: asst_0EOWZENxjwmnRZGDpDEll53p

logging:
  file:
    name: ./logs/application.log
  pattern:
    #    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    org.springframework: info
    root: error
    com.omnia: info

springdoc:
  swagger-ui:
    path: /swagger.html

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        "[http.server.requests]": true
  prometheus:
    metrics:
      export:
        enabled: true